export const buttons = [
  {
    name: "button-simple",
    bgColor: "#E0E0E0",
    color: "#3F3F3F",
    text: "Default",
    aboveText: "<Button />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-simple-hover",
    bgColor: "#AEAEAE",
    color: "#3F3F3F",
    text: "Default",
    aboveText: "&:hover, &:focus",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-outline",
    bgColor: "transparent",
    color: "#3D5AFE",
    border: true,
    borderColor: "#3D5AFE",
    text: "Default",
    aboveText: '<Button variant="outline" />',
    width: "88px",
    height: "36px",
  },
  {
    name: "button-outline-hover",
    bgColor: "#2962ff10", // 10%
    color: "#3D5AFE",
    border: true,
    borderColor: "#3D5AFE",
    text: "Default",
    aboveText: "&:hover, &:focus",
    width: "88px",
    height: "36px",
  },
  {
    name: "button-text",
    bgColor: "transparent",
    color: "#3D5AFE",
    text: "Default",
    aboveText: '<Button variant="text" />',
    width: "88px",
    height: "36px",
  },
  {
    name: "button-text-hover",
    bgColor: "#2962ff10", //  10%
    color: "#3D5AFE",
    text: "Default",
    aboveText: "&:hover, &:focus",
    width: "88px",
    height: "36px",
  },

  {
    name: "button-disableShadow",
    bgColor: "#3D5AFE",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "<Button disableShadow />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-disabled",
    bgColor: "#E0E0E0",
    color: "#9E9E9E",
    disabled: true,
    text: "Default",
    aboveText: "<Button disabled />",
    width: "88px",
    height: "36px",
  },
  {
    name: "button-disabled-text",
    bgColor: "#E0E0E0",
    color: "#9E9E9E",
    disabled: true,
    text: "Default",
    aboveText: "<Button variant=”text” disabled />",
    width: "88px",
    height: "36px",
  },
  {
    name: "button-start-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "add_shopping_cart",
    text: "Default",
    aboveText: "<Button startIcon=”local_grocery_store” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-end-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "add_shopping_cart",
    text: "Default",
    aboveText: "<Button endIcon=”local_grocery_store” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-start-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "favorite",
    text: "Default",
    aboveText: "<Button startIcon=”favorite” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-end-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "favorite",
    text: "Default",
    aboveText: "<Button endIcon=”favorite” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-start-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "star",
    text: "Default",
    aboveText: "<Button startIcon=”star” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-end-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "star",
    text: "Default",
    aboveText: "<Button endIcon=”star” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-start-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "sentiment_satisfied",
    text: "Default",
    aboveText: "<Button startIcon=”sentiment_satisfied” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-end-icon",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    hasIcon: true,
    iconClass: "material-symbols-outlined ",
    icon: "sentiment_satisfied",
    text: "Default",
    aboveText: "<Button endIcon=”sentiment_satisfied” />",
    width: "105px",
    height: "36px",
  },
  {
    name: "button-sm",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "<Button size=”sm” />",
    width: "73px",
    height: "32px",
  },
  {
    name: "button-md",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "<Button size=”md” />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-lg",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "<Button size=”lg” />",
    width: "93px",
    height: "42px",
  },
  {
    name: "button-default",
    bgColor: "#E0E0E0",
    color: "#3F3F3F",
    text: "Default",
    aboveText: "<Button color=”default” />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-primary",
    bgColor: "#2962FF",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "<Button color=”primary” />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-secondary",
    bgColor: "#455A64",
    color: "#FFFFFF",
    text: "Secondary",
    aboveText: "<Button color=”secondary” />",
    width: "104px",
    height: "36px",
  },
  {
    name: "button-danger",
    bgColor: "#D32F2F",
    color: "#FFFFFF",
    text: "Danger",
    aboveText: "<Button color=”danger” />",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-default-hover",
    bgColor: "#AEAEAE",
    color: "#3F3F3F",
    text: "Default",
    aboveText: "&:hover, &:focus",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-primary-hover",
    bgColor: "#0039CB",
    color: "#FFFFFF",
    text: "Default",
    aboveText: "",
    width: "81px",
    height: "36px",
  },
  {
    name: "button-secondary-hover",
    bgColor: "#1C313A",
    color: "#FFFFFF",
    text: "Secondary",
    aboveText: "",
    width: "104px",
    height: "36px",
  },
  {
    name: "button-danger-hover",
    bgColor: "#9A0007",
    color: "#FFFFFF",
    text: "Danger",
    aboveText: "",
    width: "81px",
    height: "36px",
  },
];
